export const START_LOADING = 'START_LOADING';
export const FETCH_SEARCH_RESULT = 'FETCH_SEARCH_RESULT';
export const CLEAR_SEARCH_RESULT = 'CLEAR_SEARCH_RESULT';
export const END_LOADING = 'END_LOADING';